### ISSUE TITLE
question about visualize

### ISSUE THREAD

**Issue by kingofstu** [mengtan00/SA-BEV#5]
Hi, how can I get visualization results like figure1 in your paper

**Comment by mengtan00** [comment]
Hi, for visualization, the absolute values of BEV feature are obtained at first, which are summed along the channel dimension. After that, the values are taken in logarithms to narrow the gap between the center and the edge of the BEV space.

**Comment by kingofstu** [comment]
> Hi, for visualization, the absolute values of BEV feature are obtained at first, which are summed along the channel dimension. After that, the values are taken in logarithms to narrow the gap between the center and the edge of the BEV space.

Thanks a lot, can I ask for the code about the viualizer? In addition, I have read your new work 'GeoBEV', how do you filtered out the background in Figure 1, appreciate it for your reply again! Best wish!

**Comment by mengtan00** [comment]
Thanks for your attention to our works. The code is as follow:
```
feats = np.log(feats.abs().sum(1)+1) 
feats = np.clip(feats,0, 5)
img=(feats/5*255).astype(np.uint8)
```
SA-BEV uses the foreground masks predicted by itself to remove the background in semantic-aware BEV features.

As for GeoBEV,  the log is removed since RC-Sampling generates dense and even BEV feature. The background in Fig 1 is filtered by foreground masks provided by a pretrained segmentation model, which help optimize the In-Box label as shown in Fig 4(d).

**Comment by kingofstu** [comment]
Thanks!
